#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

$app = new App([
    'app_path' => __DIR__ . '/cli/Command',
    'debug' => true,
]);

$app->setSignature('./code-generator help');

$app->runCommand($argv);
